[build]
  # No service worker - removed to prevent 404 errors
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  # Environment variables should be set in the Netlify dashboard
  # Do not put actual API keys in this file or in the code

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cache control for static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
